### ISSUE TITLE
Uppdatera med nu känd best practice

### ISSUE THREAD

**Issue by sesam** [ViktigtMeddelande/ViktigtMeddelande#1]
T ex "ASIC-container" som används av Lantmäteriverket, eller något därav inspirerat som gör meddelandet enklare att copypejsta

**Comment by jeorgen** [comment]
Jag ska fixa det! :)
Det är dock inte något Lantmäteriet använder (vad jag vet), utan vad vi använde i ett blockkedjeprojekt där de är med!

**Comment by jeorgen** [comment]
Fixat i commit #61c2c30ff1e992ac7673ed790133bae0cbdbb847
